version: '3.8'

services:
  ibmmq:
    image: icr.io/ibm-messaging/mq:latest
    container_name: ibmmq
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: passw0rd
      MQ_ADMIN_PASSWORD: passw0rd
    volumes:
      - qm1data:/mnt/mqm

volumes:
  qm1data:
